name = "Battlefield"
author = "Gleso"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac409eb6a49124c11ea7591735df3c60f4ba8d414e65d6ee45701a9ff8032e2d"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
