name = "Battlefield"
author = "Gleso"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9faeb0e38f0c4271457935a1a66ef7ded7539bda74cda27364474615f38b413"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
