name = "Battlefield"
author = "Gleso"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afffd083929264c0f1de25adc0ce76a9673f18bf8e7923906bb522e4264a399b"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
